# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy Contract Service 
on: [workflow_dispatch]

env:
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}
  PLATFORM: "virtual"
  CONTAINER_NAME: "contract-ledger"

jobs:    
  deploy-contract-service:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}

      - name: Setup python venv
        run: sudo apt install python3.8-venv -y

      - name: Stop previous instances
        run: docker stop $CONTAINER_NAME || true 

      - name: Build contract service container
        run: cd ${{ github.workspace }}/implementation/external/contract-ledger && ./docker/build.sh
        
      - name: Run contract service
        run: cd ${{ github.workspace }}/implementation/external/contract-ledger && ./docker/run-dev.sh 

      - name: Wait until service is running
        run: >
          timeout 60 bash -c "while ! curl -s -f -k https://localhost:8000/parameters > /dev/null; do echo \"Wating...\"; sleep 10; done"